### ISSUE TITLE
No files are downloaded

### ISSUE THREAD

**Issue by FarestR06** [RubixDev/carpet-config-creator#1]
![Screenshot 2024-02-19 at 11 55 36 AM](https://github.com/RubixDev/carpet-config-creator/assets/123666231/44c9feb9-66ab-4d69-911f-6d2707ed10cf)
Browser: Edge (Chromium); I also had this issue on Firefox
To replicate:
1. Change any settings
2. Click download
3. The download fails because no files are attached.

**Comment by RubixDev** [comment]
Thank you! I have no clue why it stopped working, I was using the `file-saver` npm package and that seems to have stopped working :shrug:. The download should now be working again though, and I also added a popup displaying the contents of the generated config file in case the download ever breaks again. Can you please confirm it's now working for you?

**Comment by FarestR06** [comment]
Yep, it's working now. Thanks!
